import { Card, CardContent, CardHeader, CardTitle } from "./ui/card";
import { Users, UserCog, UserCheck } from "lucide-react";
import { GraphCard } from "./GraphCard";

const stats = [
  {
    title: "Owners",
    count: 12,
    icon: UserCog,
    bgColor: "bg-blue-50",
    iconColor: "text-blue-600",
  },
  {
    title: "Managers",
    count: 8,
    icon: UserCheck,
    bgColor: "bg-green-50",
    iconColor: "text-green-600",
  },
  {
    title: "Guests",
    count: 156,
    icon: Users,
    bgColor: "bg-purple-50",
    iconColor: "text-purple-600",
  },
];

const pgsAddedData = [
  { month: "Aug", count: 0 },
  { month: "Sep", count: 1 },
  { month: "Oct", count: 1 },
  { month: "Nov", count: 0 },
  { month: "Dec", count: 1 },
  { month: "Jan", count: 1 },
  { month: "Feb", count: 0 },
];

const ownersAddedData = [
  { month: "Aug", count: 1 },
  { month: "Sep", count: 2 },
  { month: "Oct", count: 1 },
  { month: "Nov", count: 1 },
  { month: "Dec", count: 2 },
  { month: "Jan", count: 3 },
  { month: "Feb", count: 2 },
];

const roomsAddedData = [
  { month: "Aug", count: 0 },
  { month: "Sep", count: 15 },
  { month: "Oct", count: 25 },
  { month: "Nov", count: 0 },
  { month: "Dec", count: 30 },
  { month: "Jan", count: 20 },
  { month: "Feb", count: 0 },
];

const revenueFlowData = [
  { month: "Aug", revenue: 15000 },
  { month: "Sep", revenue: 17500 },
  { month: "Oct", revenue: 19000 },
  { month: "Nov", revenue: 20500 },
  { month: "Dec", revenue: 22000 },
  { month: "Jan", revenue: 23500 },
  { month: "Feb", revenue: 25000 },
];

export function Dashboard() {
  return (
    <div className="p-4 md:p-8">
      {/* Welcome Section */}
      <div className="mb-6 md:mb-8">
        <h1 className="text-2xl md:text-3xl font-bold text-gray-900">Welcome, Admin</h1>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4 md:gap-6 mb-6 md:mb-8">
        {stats.map((stat) => {
          const Icon = stat.icon;
          return (
            <Card key={stat.title} className="border-gray-200">
              <CardHeader className="flex flex-row items-center justify-between pb-2">
                <CardTitle className="text-sm font-medium text-gray-600">
                  {stat.title}
                </CardTitle>
                <div className={`p-2 rounded-lg ${stat.bgColor}`}>
                  <Icon className={`w-5 h-5 ${stat.iconColor}`} />
                </div>
              </CardHeader>
              <CardContent>
                <div className="text-2xl md:text-3xl font-bold text-gray-900">{stat.count}</div>
              </CardContent>
            </Card>
          );
        })}
      </div>

      {/* Analytics Graphs - 2x2 Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 md:gap-6">
        {/* Revenue Flow for RUFRENT */}
        <GraphCard
          title="Revenue Flow for RUFRENT"
          subtitle="Monthly revenue generated by RUFRENT"
          data={revenueFlowData}
          dataKey="revenue"
          xAxisKey="month"
          chartType="line"
          color="#8b5cf6"
          height={300}
          formatter={(value) => `₹${Number(value).toLocaleString()}`}
        />

        {/* Number of PGs Added */}
        <GraphCard
          title="Number of PGs Added"
          data={pgsAddedData}
          dataKey="count"
          xAxisKey="month"
          chartType="line"
          color="#3b82f6"
          height={300}
          formatter={(value) => `${value} PG(s)`}
        />

        {/* Number of Owners Added */}
        <GraphCard
          title="Number of Owners Added"
          data={ownersAddedData}
          dataKey="count"
          xAxisKey="month"
          chartType="line"
          color="#10b981"
          height={300}
          formatter={(value) => `${value} Owner(s)`}
        />

        {/* Number of Rooms Added */}
        <GraphCard
          title="Number of Rooms Added"
          data={roomsAddedData}
          dataKey="count"
          xAxisKey="month"
          chartType="line"
          color="#f59e0b"
          height={300}
          formatter={(value) => `${value} Room(s)`}
        />
      </div>
    </div>
  );
}